repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        files: \.js$
        entry: eslint
        language: node

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: "^(lerna.json)"
