repos:
  -   repo: local
      hooks:
      -   id: eslint
          name: eslint
          files: \.js$
          entry: eslint
          language: node

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
